[profile.default]
src = "src"
out = "out"
test="test"
libs = ["lib"]
solc = "0.8.26"

[rpc_endpoints]
etherum = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
optimism-sepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"

# Etherscan config in .env file
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = "sepolia" }
optimism-sepolia = { key = "${OPTIMISMSCAN_API_KEY}", chain = "optimism-sepolia" }